### ISSUE TITLE
package is not availlable on npmjs.com

### ISSUE THREAD

**Issue by mathroc** [graphile-contrib/pg-order-by-related#1]
> $ yarn add @graphile-contrib/pg-order-by-related
yarn add v1.10.1
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@graphile-contrib%2fpg-order-by-related: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/scripts/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by mattbretl** [comment]
@benjie Negative

**Comment by benjie** [comment]
Published, plus you should have access to publish in future. Please use `npm version` to change the version (and tag in git) before releasing 👍
