### ISSUE TITLE
Dependency crash

### ISSUE THREAD

**Issue by frankdugan3** [graphile-contrib/pg-order-by-related#11]
The plugin crashes on start: It seems that the dependency detection doesn't correctly parse the format used in the beta release of `graphile-build-pg`:
```
Error: Plugin @graphile-contrib/pg-order-by-related@1.0.0-beta.4 requires graphile-build-pg@^4.1.0 (current version: 4.4.0-beta.3)
```

If I comment out the dependency check, it appears to run fine.

**Comment by mattbretl** [comment]
Confirmed. The hasVersion method in PostGraphile core doesn't allow pre-releases to satisfy the range. Once this is merged it should work: https://github.com/graphile/graphile-engine/pull/419

**Comment by benjie** [comment]
Thanks for bringing this to our attention; Matt's PR has been merged and will go out with the next release.
