### ISSUE TITLE
feat: order by collection column min/max

### ISSUE THREAD

**Issue by tatethurston** [graphile-contrib/pg-order-by-related#15]
Feature request: Extend ordering options for one-to-many relations with min/max semantics. Possibly `__MIN_COLUMN_ASC` / `__MAX_COLUMN_ASC`

Last 10 distinct people who created a post:
```graphql
{

  allPersons(orderBy: POSTS_BY_AUTHOR_ID__MAX_CREATED_AT_DESC, first: 10) {
    nodes {
      id
      name
    }
  }
}
```

**Comment by mattbretl** [comment]
This is now available in v1.0.0-beta.6. You'll need to pass `orderByRelatedColumnAggregates: true` via `graphileBuildOptions`. See the README for an example.
