### ISSUE TITLE
When ordering by related record, the pageInfo is showing incorrect meta data

### ISSUE THREAD

**Issue by jcfinnerup** [graphile-contrib/pg-order-by-related#19]
When i order by a related record, the edges.pageInfo child of all the records, has some incorrect meta data. 

The `endCursor`, `startCursor` and `hasNextPage` are null, and no results are returned, even though the totalCount is still 84.

It works fine if i do not use the "after" parameter in the query. Once i supply an "after", the pageInfo breaks

I might just be doing something wrong. 

Any help is greatly appreciated!
Cheers

**Comment by mattbretl** [comment]
Can you share the actual GraphQL query where you're seeing this issue? The `after` arg requires an opaque cursor (the `nodeId` you see on Connections); if you feed it an unrecognized value, you'll get an empty result set just like you described.

**Comment by mattbretl** [comment]
It appears to be working based on this example:

```sql
create table p.foo (
  id integer primary key,
  foo_name text not null
);

create table p.bar (
  id integer primary key,
  bar_name text not null,
  foo_id integer references p.foo (id)
);

insert into p.foo (id, foo_name) values
  (1, 'a'),
  (2, 'b'),
  (3, 'c'),
  (4, 'd');

insert into p.bar (id, bar_name, foo_id) values
  (1, 'one', 1),
  (2, 'two', 2),
  (3, 'three', 3),
  (4, 'four', 4);
```
```graphql
{
  allBars(first: 2, orderBy: FOO_BY_FOO_ID__FOO_NAME_DESC) {
    nodes {
      barName
      fooByFooId {
        fooName
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
```
```json
{
  "data": {
    "allBars": {
      "nodes": [
        {
          "barName": "four",
          "fooByFooId": {
            "fooName": "d"
          }
        },
        {
          "barName": "three",
          "fooByFooId": {
            "fooName": "c"
          }
        }
      ],
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
        "startCursor": "WyJmb29fYnlfZm9vX2lkX19mb29fbmFtZV9kZXNjIixbImQiLDRdXQ==",
        "endCursor": "WyJmb29fYnlfZm9vX2lkX19mb29fbmFtZV9kZXNjIixbImMiLDNdXQ=="
      }
    }
  }
}
```
```graphql
{
  allBars(
    first: 2
    after: "WyJmb29fYnlfZm9vX2lkX19mb29fbmFtZV9kZXNjIixbImMiLDNdXQ=="
    orderBy: FOO_BY_FOO_ID__FOO_NAME_DESC
  ) {
    nodes {
      barName
      fooByFooId {
        fooName
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
```
```json
{
  "data": {
    "allBars": {
      "nodes": [
        {
          "barName": "two",
          "fooByFooId": {
            "fooName": "b"
          }
        },
        {
          "barName": "one",
          "fooByFooId": {
            "fooName": "a"
          }
        }
      ],
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": true,
        "startCursor": "WyJmb29fYnlfZm9vX2lkX19mb29fbmFtZV9kZXNjIixbImIiLDJdXQ==",
        "endCursor": "WyJmb29fYnlfZm9vX2lkX19mb29fbmFtZV9kZXNjIixbImEiLDFdXQ=="
      }
    }
  }
}
```

**Comment by benjie** [comment]
If `after` is invalid you'll get no results/cursors/etc (but currently you won't get an error; we might add an error for this in v5). You need to supply the `cursor` value from a cursor in the _same_ `orderBy` for it to work - if you change `orderBy` then the old cursor is no longer valid.

**Comment by jcfinnerup** [comment]
Sorry for my absense, and thanks a lot for your response. 
I've checked that the cursor is updated correctly when the order param is changed, and is seems to be fine. I still have the issue however, so ill paste the two queries and the results below: 

## First Query
```
query {
all_candidates(
    first: 25, 
    orderBy: ADDRESS_BY_ADDRESS_ID__CITY_ASC
  ) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    nodes {
      id
    }
  }
}
```

## First Result
```
{
  "data": {
    "all_candidates": {
      "totalCount": 99,
      "pageInfo": {
        "endCursor": "WyJhZGRyZXNzX2J5X2FkZHJlc3NfaWRfX2NpdHlfYXNjIixbbnVsbCwiMzYzYjQwYzAtNTZhYi0xMWU5LTk0MjQtMjVkZDQ2MmFhYTdlIl1d",
        "hasNextPage": true
      },
      "nodes": [
        {
          "id": "9741e850-7ba5-11e9-9759-1f73744fd3f6"
        },
        {
          "id": "5de6a850-9d76-11e9-8e8f-31a2d8c88bd9"
        },
        {
          "id": "671a48d0-9d6e-11e9-8e8f-31a2d8c88bd9"
        },
        {
          "id": "a4bdbee0-9cd0-11e9-bb16-3f4751b7c381"
        },
        ... 
``` 

This is perfectly as i'd expect. Now when i supply the endCursor to the query, the **pageInfo** gets weird.  

## Second Query
``` 
query {
  all_candidates(
    after: "WyJhZGRyZXNzX2J5X2FkZHJlc3NfaWRfX2NpdHlfYXNjIixbbnVsbCwiMzYzYjQwYzAtNTZhYi0xMWU5LTk0MjQtMjVkZDQ2MmFhYTdlIl1d", 
    first: 25, 
    orderBy: ADDRESS_BY_ADDRESS_ID__CITY_ASC
  ) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    nodes {
      id
    }
  }
}
``` 

## Second Result 

``` 
{
  "data": {
    "all_candidates": {
      "totalCount": 99,
      "pageInfo": {
        "endCursor": null,
        "hasNextPage": false
      },
      "nodes": []
    }
  }
}
```

**Comment by benjie** [comment]
If you base64 decode your cursor, it comes out as: `["address_by_address_id__city_asc",[null,"363b40c0-56ab-11e9-9424-25dd462aaa7e"]]`

That null is what’s causing the issues. Can you shed any light @mattbretl; perhaps we’re somehow not constructing this cursor correctly?

**Comment by mattbretl** [comment]
It does appear to be related to that `null`. But I don't think it's anything specific to this plugin. Here's a simple repro with vanilla PostGraphile:

```sql
create table p.address (
  id integer primary key,
  city text
);
```
```graphql
{
  page1: allFoos(first: 2, orderBy: NAME_ASC) {
    nodes {
      id
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
  page2: allFoos(
    first: 2
    orderBy: NAME_ASC
    after: "WyJuYW1lX2FzYyIsW251bGwsMl1d"
  ) {
    nodes {
      id
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
}
```
```
{
  "data": {
    "page1": {
      "nodes": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ],
      "pageInfo": {
        "endCursor": "WyJuYW1lX2FzYyIsW251bGwsMl1d",
        "hasNextPage": true
      },
      "totalCount": 4
    },
    "page2": {
      "nodes": [],
      "pageInfo": {
        "endCursor": null,
        "hasNextPage": false
      },
      "totalCount": 4
    }
  }
}
```

**Comment by benjie** [comment]
Well that’s super weird; we construct the cursor in SQL, so it shouldn’t put a null in...

https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build-pg/src/queryFromResolveDataFactory.js#L294

Ohhhhhh! It’s because the thing itself is nullable! Sorting by a nullable thing risks the cursor having a null in, and a cursor with a null in currently can’t be used for pagination.

So we have to massively complicate our pagination SQL logic to deal with this; and that will be a performance penalty for everyone, unless we can find a way of indicating if the relevant field is nullable or not.

Please someone file this against graphile-engine. (Or I will in the week.)

**Comment by benjie** [comment]
Promoted to Graphile Engine: https://github.com/graphile/graphile-engine/issues/502
