### ISSUE TITLE
duplicate names when multiple FK to the same table

### ISSUE THREAD

**Issue by mathroc** [graphile-contrib/pg-order-by-related#4]
eg: the stamp table holds data and session information about thing that happens, many table have multiple foreign key to this table (ie: created, update, etc.)

in that case, as the generated name only uses names from the foreign table, it generates the same name multiple times:

> unhandled rejected promise Error: A naming conflict has occurred - two entities have tried to define the same key 'STAMP__AT_ASC'.
  The first entity was:
    Adding ascending orderBy enum value for column "at" on table "graphql"."stamp". You can rename this field with:
      COMMENT ON COLUMN "graphql"."stamp"."at" IS E'@name newNameHere\nThe moment an event occured';
  The second entity was:
    Adding ascending orderBy enum value for column "at" on table "graphql"."stamp". You can rename this field with:
      COMMENT ON COLUMN "graphql"."stamp"."at" IS E'@name newNameHere\nThe moment an event occured';

I've used this inflector to solve the problem:

```js
orderByRelatedColumnEnum(attr, ascending, foreignTable, keys) {
	return `${
		keys.map(({name}) => name).join("-and-").toUpperCase()
	}_${this.orderByColumnEnum(attr, ascending)}`;
},
```

but to do that, I had to add the `keys` argument to the inflector.

I don't know if you want to change how the name is generated to add the keys name, but at least the keys should be available to the inflector

**Comment by mattbretl** [comment]
Agreed. I'll add `keys` and update the default inflector.

**Comment by mattbretl** [comment]
`beta.1` has the update. I just published it to npm.

**Comment by mathroc** [comment]
awesome, it's working perfectly :grinning: thank you again @mattbretl !
